### ISSUE TITLE
ImportError: No module named 'analysis_tools'

### ISSUE THREAD

**Issue by dbdxnuliba** [super-owesome/bobble_controllers#13]
Traceback (most recent call last):
  File "make_plots.py", line 54, in <module>
    main()
  File "make_plots.py", line 49, in main
    df, pc = load_data(args.run, run_name)
  File "make_plots.py", line 12, in load_data
    from analysis_tools.parsing import parse_single_run
ImportError: No module named 'analysis_tools'

**Comment by dbdxnuliba** [comment]
I SEE ，I should use python2 but not python3
